### PR TITLE
Add ruby 2.7

### PR DESCRIPTION
**Pull request by knu**
This adds Ruby 2.7.1 and 2.7.0.  I'll rebase this after #187 gets merged.

### CODE REVIEW

**Comment by ain** [comment]
Any news here guys?

**Comment by knu** [comment]
Perhaps it's time for the rest of us to learn how to home-brew the prebuilt images.

@dazuma Any chance this gets looked at?

**Comment by dazuma** [comment]
Hey, sorry for the delay. I built the prebuilt images, will merge this and the earlier PR once testing is complete.

**Comment by ain** [comment]
@dazuma that'd be great as this is also bound to some Google services that make life so much easier + faster. Thanks a lot for the great work!

**Comment by dazuma** [comment]
Note: when resolving conflicts, I reverted the "default" versions back to 2.6.6 for the moment. This is because the API clients stack is still more stable on 2.6.

**Comment by dazuma** [comment]
Thanks! We'll start the process of releasing a runtime update.

**Pull request merged**
