### PR TITLE
Add Ruby 3.0.1, 3.0.0, 2.7.3, 2.6.7 and 2.5.9

### PR DESCRIPTION
**Pull request by knu**
Ruby 3.0.0 was released two months ago.  This PR adds 3.0.0 to the list of rubies.

### CODE REVIEW

**Comment by knu** [comment]
New teeny releases have been added.  /ping @dazuma 🙏

**Comment by knu** [comment]
This project seems to be on hiatus, but fortunately, the [Dockerfile template](https://github.com/GoogleCloudPlatform/ruby-docker/blob/master/ruby-prebuilt/Dockerfile.in) is so simple and you can easily build prebuilt ruby images on your own.

```Dockerfile
FROM gcr.io/gcp-runtimes/ruby/ubuntu16:latest AS builder
ARG ruby_version
RUN cd ${RBENV_ROOT}/plugins/ruby-build \
    && git pull \
    && rbenv install -s ${ruby_version}

FROM scratch
ARG ruby_version
COPY --from=builder \
     /opt/rbenv/versions/${ruby_version} \
     /opt/rbenv/versions/${ruby_version}
```

**Comment by dazuma** [comment]
You're right, I haven't been monitoring this as well I should. This looks fine. The changes to CI won't pass until we actually build the new versions, and we need them in master in order to do that, so I'll go ahead and merge this for now.

**Review by dazuma — APPROVED** [review]

**Comment by knu** [comment]
@dazumu Thank you for coming back and taking the time.  I really appreciate it!

**Pull request merged**
