### PR TITLE
adding license tests to ruby structure tests

### PR DESCRIPTION
**Pull request by sharifelgamal**
License tests are automated tests to check that all packages installed in the image conform to Google's open source licensing stardards. Check out https://github.com/GoogleCloudPlatform/runtimes-common/blob/master/structure_tests/licenses_test.go (and the corresponding README) for more details.

### CODE REVIEW

**Comment by nkubala** [comment]
hmm. maybe we should also have a structure test just verifying this file is here in the first place?

**Comment by sharifelgamal** [comment]
If you're talking about /nodejs/LICENSE, then the test will fail if the file isn't there.

**Comment by nkubala** [comment]
also, wait a minute. this is testing the /nodejs/LICENSE in the ruby image?

**Comment by hxiong388** [comment]
I was wondering the same thing. The Ruby base image downloads and installs NodeJS. But why are we checking LICENSE when the the NodeJS is installed from nodejs.org?

**Comment by sharifelgamal** [comment]
The entire point of the files option in the license tests is to check anything that is installed, but not through apt. It's to keep everything consistent, and to remind people to check stuff that's wget'ted or curled in the Dockerfile.

**Pull request merged**
